Solicitud de rpmacal2013
luxur3000/nueva-legion pull request #1
Opened 2020-09-01 17:30 UTC by rpmacal2013

### Modificaciones

- Se agregan dos villanos
- Se crea la solicitud de rpmacal2013

2020-09-01 17:36 UTC, luxur3000 requested changes
Por favor no agregar más villanos.

2020-09-01 17:36 UTC, luxur3000 commented on miembros.md
> +24. Darkseid
Ya no es necesario agregar más villanos.

2020-09-01 17:42 UTC, rpmacal2013 commented on miembros.md
> +24. Darkseid
De acuerdo

2020-09-08 18:28 UTC, luxur3000 approved these changes
Aprobado

2020-09-08 18:30 UTC, luxur3000 commented
Correcto todo.

2020-09-08 18:30 UTC, closed without merging